### ISSUE TITLE
entity_index_build_query_string() pagination

### ISSUE THREAD

**Issue by alxkolm** [signalpoint/jDrupal#18]
`entity_index_build_query_string()` build query string with `page_size` instaed `pagesize` parameter

**Comment by signalpoint** [comment]
@alxkolm `page_size` is used because that's what Services uses: http://cgit.drupalcode.org/services/tree/services.module?h=7.x-3.x#n912

Any particular reason you want to see this change?

**Comment by alxkolm** [comment]
Because this work 
/?q=drupalgap/taxonomy_term.json&parameters[vid]=2&**pagesize**=999
but this do not work
/?q=drupalgap/taxonomy_term.json&parameters[vid]=2&**page_size**=999

And Services use `pagesize` parameter (not `page_size`) http://cgit.drupalcode.org/services/tree/resources/taxonomy_resource.inc?h=7.x-3.x#n119

**Comment by signalpoint** [comment]
@alxkolm Excellent, you are right, thank you!
