### ISSUE TITLE
clearLocalStorage()

### ISSUE THREAD

**Issue by d0t101101** [signalpoint/jDrupal#32]
Please add this custom localcache management function to Jdrupal.

```
function clearLocalStorage(contains) {
    Object.keys(localStorage) 
        .forEach(function(key){ 
        if ((new RegExp(contains)).test(key)) {
               localStorage.removeItem(key);
           }
        }); 
}
```

**Comment by silesky** [comment]
Not sure I get the reasoning here, this looks like a standard utility function? There are many other Javascript libraries that deal with localstorage.

**Comment by signalpoint** [comment]
@silesky Agreed, thank you. @d0t101101 and I were able to resolve this one on the side some time ago.
