### ISSUE TITLE
Misnamed request method in setup doc

### ISSUE THREAD

**Issue by kentr** [signalpoint/jDrupal#33]
I would do a PR, but I haven't found the doc in a github repo.

In this doc: http://cgit.drupalcode.org/jdrupal/plain/README.md, it references a `PUT` method.  I don't see that method at `admin/config/services/rest/resource/entity%3Anode/edit`, or `admin/people/permissions`, only `GET`, `POST`, `DELETE`, and `PATCH`

Suggested change:

`2. Access PUT on Content resource : Authenticated user`

to

`2. Access PATCH on Content resource : Authenticated user`

**Comment by signalpoint** [comment]
@kentr Thank you for pointing this out Kent. I've update the README and pushed it up to drupal's git repo.
