### ISSUE TITLE
jdrupal-7.0.2.min seems not working..

### ISSUE THREAD

**Issue by vinaysamant** [signalpoint/jDrupal#37]
1st thing, i should thank you from bottom of my heart for this amazing jDrupal. This is something i really really craving for. I tried DrupalGap and all your tutorials and lot of stuff online, but jDrupal is really top of the world. _While doing this i downloaded jdrupal-7.0.2 from http://jdrupal.easystreet3.com/7/docs/Download pointing to https://raw.githubusercontent.com/easystreet3/jDrupal/7.x-1.x/jdrupal.min.js. I included it properly and tried every possible setting. And nothing ever worked._ I was about to give up thinking that jDrupal must be trial experiment and 'you' must have gone ahead with DrupalGap. But then 3.45AM in morning, i decided to re-read your docs and just downloaded the source from https://github.com/easystreet3/jDrupal/releases. I just ran your app, as it is and it displayed magic words : hello world.

I am developing this app for one of my client where my specific requirement was to have "Drupal" as module and sole. DrupalGap is completely dependent on Drupal and it doesn't work at all if you are not connected. I wanted to bundle some sample data/videos for offline access and then also avail "Drupal" inside. Currently we have Opigno on Drupal and this app is being developed for educational purpose. Somehow I found jDrupal and i m thrilled. **Can you please provide more documentation and examples?** I can help you also if you want. But I am not good/geek programmer as you! But i will surely like to help. I am thinking of writing a basic tutorial on this experience that should guide rookies like me to build phonegap based mobile apps.

**Comment by signalpoint** [comment]
@vinaysamant Thank you for the kind words about jDrupal and DrupalGap. I've not sure why the jdrupal.min.js file was/is not working for you. It's backed by unit testing, but either way I'm glad it is now working for you.

You are correct that DrupalGap isn't very helpful if there is no connection. Ideally effort would be put towards better offline capability in DrupalGap. All documentation will live in the `docs` folder of each project, so please submit pull requests with any improvements you would like to add.

Thank you again for your interest, good luck and happy coding!

**Comment by vinaysamant** [comment]
@signalpoint, I have seen all the documentation regarding jDrupal, whatever is online.
Do you have anything additional to it in some archives or something?
Is this jDrupal forms base for DrupalGap?

**Comment by signalpoint** [comment]
That is all the docs that are available for jDrupal, short and sweet. It definitely could use some more examples, but I personally spend the vast majority of my time then building DrupalGap on top of jDrupal, and then documenting DrupalGap.

**Comment by vinaysamant** [comment]
hii!

one small question..
i have written a simple function to check connection using system_connect, and then whether user already logged in : if(typeof user.uid === "undefined" || user.uid == 0). I am giving link to my drupal site where he may navigate and access other inbuilt functions. But this opens in new browser window. Why is that so? Why does not it use app where we load our html?

```
            system_connect({
                success: function(result) {
                    $("#userarea").html("online now..");
                    var user = Drupal.user;
                    if(typeof user.uid === "undefined" || user.uid == 0){
                        $("#userarea").html('<a href="#" id="login" class="ui-btn-icon-left" data-role="button" data-icon="star" onclick="login()">Login</a>');
                    }
                    else {
                        $("#userarea").html("welcome back " + user.name + '!');
                        $("#userarea").append('<a href="http://test.mipconline.org/my-courses" id="mycourses" class="ui-btn-icon-left" data-role="button" data-icon="star">My Courses</a><a href="#" id="logout" class="ui-btn-icon-left" data-role="button" data-icon="star" onclick="logout()">Logout</a>');
                        node_load(20, {
                            success: function(node) {
                                alert("Loaded " + node.title);
                            }
                        });
                    }
                },

                error: function(result) {
                    alert("Network error. Unable to connect MIPC Resources.");
                }
              });
```

**Comment by vinaysamant** [comment]
hey i got it..
there is setting in config.xml : <allow-navigation href="http://test.mipconline.org/*" />
This works like wonder!
I have also deleted : 

```
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
```

This means one shall not be able to access any link from my app. Isn't it??

jDrupal Rocks! Period!

**Comment by signalpoint** [comment]
@vinaysamant Thank you for sharing the solution. I noticed it looks like you are using jQuery Mobile to build your app. If that is the case, then I _highly_ recommend checking out DrupalGap.

**Comment by vinaysamant** [comment]
Hii..

sorry for late reply.
what i m trying to develop the app is as follows : 
- App will start will offline functionality, so that users can use this app even when in aeroplane or no network areas etc.
- App shows a splash screen (original cordova plugin) and then navigates to index page. Here I am loading some OFFLINE resources like course ware, about us etc that user should be able to access even when offline.
- At same time, index.html loads jDrupal in header and checks connection. If connection is successful then it checks for 'User Login'. If user is anonymous then it shows login block with registration and password link options. But these are all local html forms, embedded in app. Not using Drupal.
- If user enters user-pass then app try to login to drupal using your jDrupal API. Same about registration and password. We are not showing single drupal page yet.
- Then after login, i show him 2 options : 1) My Courses -> connecting to Drupal-Opigno and 2) Open Source Content : Some free videos etc..
  In this entire chapter, offline access is one very important thing. Also I am thinking of allowing download of OS content that can be shared by users, which also requires offline access to app.

I think this is not possible with DrupalGap, or i dont know how!
If you have some time kindly check "https://play.google.com/store/apps/details?id=org.mipconline.jd&hl=en". This is the app. Still in beta mode. You can download and register etc.

And many thanks to you for JDrupal.

**Comment by signalpoint** [comment]
@vinaysamant Your bullet points 1-2 would be the trickiest, best of luck. Offline capabilities in DrupalGap continue to improve, but it would need to be enhanced further to function with the scenario you've described.

**Comment by kentr** [comment]
@vinaysamant I'll be doing something similar with the D8 version & Ionic.

It would be great to collaborate on a local storage model and connection detection.

**Comment by vinaysamant** [comment]
@signalpoint those points are achieved nicely. Now thinking of adding downloadable content like movies, pdfs etc that can not be bundled within the app. I like jDrupal because it does not demand anything to be installed on Drupal side. Is this same about D8 also? or do we need to install additional modules?

@kentr i will also be doing similar thing on D8 & jDrupal8. I have a D8 website developed for a MP in India can be seen at www.narendrasawaikar.org. I will be writing an app for this.. but never used ionic.
Have you tried jDrupal? My above listed app is Cordova + jDrupal. This version has offline capabilities. Next version will use local storage, downloads etc. Releasing in next week. I will post URL here.

**Comment by signalpoint** [comment]
In D8, there is a jDrupal Drupal module needed for jDrupal Connect to work, otherwise all other jDrupal calls will work without the module and just run through D8 core REST.
