### ISSUE TITLE
Are you supporting Drupal 8 ?

### ISSUE THREAD

**Issue by abdoMous** [signalpoint/jDrupal#4]

**Comment by signalpoint** [comment]
@moussaoui91 Yes, we plan to support Drupal 8 ASAP now that the Beta version has been released. Please consider contributing some code to make it happen if you'd like, thanks!

**Comment by marthinal** [comment]
@signalpoint I have attached a couple of patches to the D8 module at DO and I'm adapting jDrupal to work with. For example the request for the token is right now "/rest/session/token" using rest module.

Could you create a new branch for D8 version?

**Comment by signalpoint** [comment]
@marthinal Thank you. Just today I was sitting down to get caught up on your patches posted to DO.

I've created the 8.x-1.x branch for jDrupal: https://github.com/easystreet3/jDrupal/branches

**Comment by marthinal** [comment]
@signalpoint Don't worry. Thanks!

**Comment by signalpoint** [comment]
@moussaoui91 FYI, we've got user login and logout, plus node save and load working for Drupal 8 now. More to come...

**Comment by marthinal** [comment]
Great!!!

:)

**Comment by signalpoint** [comment]
jDrupal 8 has been released:
- https://drupal.org/project/jdrupal
- http://jdrupal.easystreet3.com
