### ISSUE TITLE
Duplicate Password Request Sent

### ISSUE THREAD

**Issue by mattshoaf** [signalpoint/jDrupal#43]
When using user_request_new_password, the password request is sent twice. Console log shows: site.com/?q=drupalgap/user/request_new_password.json jdrupal.js:1499 occurs twice.

Has anybody else ran into this? I'm using this as a dependency of DrupalGap if that makes any difference, but this doesn't happen with user updates or user logins, so I'm guessing it has more to do with jdrupal.

**Comment by signalpoint** [comment]
@mattshoaf After a quick review, I don't see anything to lead me to believe that DG would be making a double call to the Service Resource: https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/modules/user/user.forms.js

During form submission, it makes a single call.

2 repeated console log messages, may not necessarily mean it was called twice. To verify, have the Network tab open in your browser's developer tools, then simulate the situation where you saw the 2 console messages, and verify you can find either 1 or 2 actual network calls made.

**Comment by mattshoaf** [comment]
Yes, I'm seeing two POST in the network tab. Users were getting 2 emails, but I just tested again and they're only receiving one. So this is a non-issue unless it starts sending multiple emails from the site again.
