### ISSUE TITLE
IE9 Compatibility

### ISSUE THREAD

**Issue by dorianboulch** [signalpoint/jDrupal#45]
Hi,

I've just met an error with IE9, XMLHttprequest doesn't work properly while connecting.

jdrupal.js (line 355)
`var result = JSON.parse(req.response);`

To ensure compatibility, it should be :

`var result = JSON.parse(req.responseText);`

**Comment by signalpoint** [comment]
@dorianboulch Is this for jDrupal 7 or 8?

Do you happen to have a little snippet that can first check to see if it is IE9? I'd like to only make that change for IE9, and not all other browsers.

**Comment by kentr** [comment]
@signalpoint Looks like `responseText` is in the [spec](http://www.w3.org/TR/XMLHttpRequest/#the-responsetext-attribute), so maybe using it more generally would be ok.

Something like this?

```
// If req.responseText has data, use it.
// Else if req.response has data, use it (avoid breaking any browsers that currently work but don't implement responseText).
```
