### ISSUE TITLE
Drupal 8.2

### ISSUE THREAD

**Issue by Romz** [signalpoint/jDrupal#49]
Hi,

I updated drupal to 8.2, and rest ui to, but it seems that jdrupal not work anymore.

When i try to go "jdrupal/connect/?_format=json", i have a 404 error:

{"message":"No route found for \u0022GET \/jdrupal\/connect\/\u0022"}.

Is 8.2 broke jdrupal?

Thank you.

**Comment by sobi3ch** [comment]
I solve this problem few weeks ago but forget how. Only thing I'm remember now is that problem has something with new rest permisson changes https://www.drupal.org/node/2733435

**Comment by signalpoint** [comment]
@Romz and @sobi3ch jDrupal Connect is still working properly in Drupal 8.2 , the User Login was broken in Drupal 8.2 in jDrupal though. I have just fixed this issue, and user login will work with jDrupal in Drupal 8.2 now.
