### ISSUE TITLE
Update docs for Drupal 7

### ISSUE THREAD

**Issue by sobi3ch** [signalpoint/jDrupal#53]
On http://jdrupal.easystreet3.com/7/docs/Install page (point 2 2. Enable the Services Module and Create Endpoint) #you should add point like:

> Enable `rest_server` module

..otherwise there is no chance to pick up server from and save it on the end.

**Comment by signalpoint** [comment]
@sobi3ch Thank you for pointing this out, I've added a note to the docs: https://github.com/easystreet3/jDrupal/commit/ab723661ca29464eede50d5ab34a969676ca99cd
