### ISSUE TITLE
Multiple definitions of entity_delete()

### ISSUE THREAD

**Issue by jacobembree** [signalpoint/jDrupal#58]
`entity_delete()` is defined in `src/entity.js` and `src/services/services.entity.js`

`src/entity.js` `entity_delete()` calls `entity_type + '_delete'`.
`src/services/services.entity.js` `entity_delete()` uses `Drupal.services.call()`.

I believe the one in `services.entity.js` overwrites the one in `entity.js`, so should the one in `entity.js` simply be removed?

**Comment by signalpoint** [comment]
@jacobembree Yes, great catch, thank you.
