### ISSUE TITLE
How to update user account fields supported?

### ISSUE THREAD

**Issue by giorgio79** [signalpoint/jDrupal#6]
I was looking at the user examples https://www.easystreet3.com/jDrupal/users

Looks like the user update example is missing. Would love to see an example for updating a user with fields.

**Comment by signalpoint** [comment]
@giorgio79 This should work:

```
var account = {
  uid: 123,
  name: 'bob',
  field_text: {
    'und': [
      { value: 'abc'; }
    ]
  }
};
user_save(account, {
  success: function(result) {
    console.log(result);
    alert('Saved user');
  }
});
```

Please confirm if it does or does not work. Turn on `Drupal.settings.debug = true;` to watch important console log messages.

**Comment by giorgio79** [comment]
Oh Wow. That's beautiful :) Works like magic.

**Comment by EnzoEghermanne** [comment]
@signalpoint Is there any way to do this in jDrupal 8?
I'm looking for a way to edit a field from the jDrupal.currentUser() and then save it.
