### ISSUE TITLE
Hook for error handling

### ISSUE THREAD

**Issue by giorgio79** [signalpoint/jDrupal#7]
Hello,

I noticed all errors are output via console.

I would love a hook for errors (I would like to provide a popup for the users etc)

**Comment by signalpoint** [comment]
@giorgio79 For now, the best way to catch errors is by using the `error` callback when making any Service calls. For example:

```
user_load(123, {
  success: function(account) {
    alert(account.name);
  },
  error: function(xhr, status, message) {
    alert(message);
  }
});
```

Other than that, all errors are internal to jDrupal, and at this point there isn't a hook to do what is requested. Perhaps a `Drupal.console.log();` function could be created to output stuff to the console, and it could come with a hook(s) to make that happen.

**Comment by giorgio79** [comment]
Beautiful! I thought jdrupal would override that. :)
