### ISSUE TITLE
Can you make jDrupal worked with NodeJS and Webpack?

### ISSUE THREAD

**Issue by VienDinhCom** [signalpoint/jDrupal#77]
Hi there,

I saw that this is an awesome drupal module. However, it would be better if Drupal could work with NodeJS and Webpack.

Can you do that? Thanks :smile:

**Comment by signalpoint** [comment]
@Maxvien Do you mean make it available as an npm package?

**Comment by VienDinhCom** [comment]
Yup, I mean that :+1: 

I tried to do this, but it didn't work.

`import * as jdrupal from 'jdrupal/jdrupal';`

**Comment by signalpoint** [comment]
@Maxvien Hmmm, it looks like I published it for npm long ago: https://www.npmjs.com/package/jdrupal

Their version is pointing to easystreet3/jDrupal, which on github's side now redirects to signalpoint/jDrupal.

Are you able to use something like `signalpoint/jDrupal` to get around it? Any ideas?

**Comment by VienDinhCom** [comment]
Okay, let me check it.
Thanks very much :smile:
