### ISSUE TITLE
jDrupal's "Drupal" JSON object collides with Drupal's "Drupal" JSON object

### ISSUE THREAD

**Issue by giorgio79** [signalpoint/jDrupal#9]
Hello,

I love jDrupal. I just tried adding it to a Drupal site due to the fantastic interface, but I am getting js errors. Looks like the Drupal vars are clashing.

 Uncaught TypeError: undefined is not a function

Failing on these lines

//Attach all behaviors.
$(function () {
  Drupal.attachBehaviors(document, Drupal.settings);
});

**Comment by signalpoint** [comment]
@giorgio79 Thanks for pointing this out. Do you happen to be a JavaScript wizard and know how we can get around it?

The only thing I can think of is to rename jDrupal's usage of `Drupal` to `jDrupal` throughout the project.

**Comment by signalpoint** [comment]
@giorgio79 I say this because I've never tried to put jDrupal in a Drupal environment, I've always had jDrupal "stand alone" and then talk to a Drupal site. But I can see how it would collide if jDrupal was included in a Drupal environment.

**Comment by giorgio79** [comment]
Yep, the easiest solution would be to change the namespace. jQuery uses some noconflist magic, but I am unaware what is going on in the background (http://stackoverflow.com/questions/7937507/how-to-encapsulate-jquery)
The reason I am including it in Drupal is because I am ditching the Flag module in favor of jDrupal among other reasons :) jDrupal allows a fantastic user experience.

**Comment by signalpoint** [comment]
@giorgio79 Ok, you're right, I really should just change the namespace to `jDrupal`. It'll be a while before I get a chance to do this, if you'd like, please make a fork of jDrupal and you can get started on it, then submit a pull request.

My main concern is all the DrupalGap app's out there dependent on the existence of `Drupal`, they'll all have to change to `jDrupal`. With progress comes change though!

**Comment by giorgio79** [comment]
Just created the pull. Works fine for me! :)
